### ISSUE TITLE
Create next-auth authorization

### ISSUE THREAD

**Issue by Security2431** [Security2431/2day-report#11]
#### DOCS:
- [ ] next-auth auth https://dev.to/franciscomendes10866/nextjs-authentication-with-next-auth-trpc-and-prisma-kgl
- [ ] next authorization with prisma and email https://github.com/danyel117/wanda/blob/main/pages/api/auth/%5B...nextauth%5D.ts
- [ ] ❗  secure routes in nextjs https://www.freecodecamp.org/news/secure-routes-in-next-js/
- [ ] configuration auth pages https://next-auth.js.org/configuration/pages
- [ ] Next-auth athorization https://medium.com/@rezahedi/using-nextauth-authentication-provider-in-next-js-by-app-router-f50cb23282c9
- [ ] Next auth providers https://blog.stackademic.com/next-js-13-authentication-with-nextauth-js-app-router-typescript-641058805bc3
- [ ] next-auth session provider https://medium.com/@rohitkumarkhatri/next-auth-in-app-router-of-next-js-7df037f7a2ad
- [ ] auth with rbac https://github.com/gitdagray/next-auth-role-based/blob/main/src/app/api/auth/%5B...nextauth%5D/options.ts
- [ ] rbac https://dev.to/musebe/implementing-role-based-access-control-in-nextjs-app-router-using-clerk-organizations-566g

#### TODO:
- [x] Email provider
- [x] Google provider
- [x] Github provider
- [ ] if user already signed up with credential an trynna sign in /w providers. Then, send him an email address and link this provider to his account
